
    <option value="">المرجو الاختيار</option>
    <option value="sempol">التقرير المبسط</option>   
    <option value="sempol_land">تقرير الهيئة ارض </option>  
    <option value="sempol_con">تقرير الهيئة انشاء </option>  
    <option value="sempol_sk">تقرير الهيئة سكني </option>  
    <option value="sst"> البنك السعودي للأستثمار</option>
    <option value="sempol_e">التقرير المبسط انجليزي</option>
    <option value="alrajhi_ind">مصرف الراجحي - أفراد</option>
    <option value="alrajhi_cmp">مصرف الراجحي - شركات</option>
    <option value="alrajhi_m">مصرف الراجحي ممتلكات - أفراد</option>
    <option value="sfc">البنك السعودي الفرنسي - شركات</option>
    <option value="sfc_ind">البنك السعودي الفرنسي - أفراد</option>
    <option value="riyadh_cmp">بنك الرياض - التوثيق والضمانات</option>
    <option value="riyadh_com">بنك الرياض -  شركات</option>
    <option value="riyadh_afrad">بنك الرياض - افراد</option>
    <option value="riyadh">عام مختصر - أفراد</option>
    <option value="amlak">شركة أملاك - أفراد</option>
    <option value="shb">البنك الاول - أفراد</option>
    <option value="inma">بنك الانماء - أفراد</option>
    <option value="shl">سهل - أفراد</option>
    <option value="bidaya_ind">بداية - أفراد</option>
    <option value="sab">ساب - عام</option>
    <option value="sab_est">ساب - استصناع - (كريم)</option>
    <option value="sab0">تقرير زيارة</option>
    <option value="samba_handace">سامبا - هندسي</option>
    <option value="samba_land">سامبا - ارض</option>
    <option value="samba_fela">سامبا - فيلا</option>
    <option value="jazera_afrad">بنك الجزيرة - افراد</option>
    <option value="jazera_est">بنك الجزيرة - بناء ذاتي</option>
    <option value="ahli">البنك الاهلي </option>
    <option value="ahli_est">البنك الاهلي استصناع </option>
    <option value="dar_altamlek">شركة دار التمليك </option>
    <option value="blad">بنك البلاد </option>
    <option value="afrad">عملاء افراد </option>
    <option value="shmol">شركة شمول العقارية </option>
    <option value="stampol">شركة إسطول الانجاز التجارية المحدودة </option>
    <option value="tmaioz">شركة التميز العقارية </option>
    <option value="stc">بيع - STC</option>
    <option value="stc_rent">تأجير - STC</option>
    <option value="blad_blad">  بلاد بنك البلاد </option>
    <option value="alrajhi_est_1">مصرف الراجحي - بناء جديد</option>
    <option value="alrajhi_est_2">مصرف الراجحي -  اكمال البناء</option>
    <option value="alrajhi_est_3">مصرف الراجحي -  اكمال البناء ما بعد الحفر</option>
    <option value="alrajhi_est_4">مصرف الراجحي -   البناء ر</option>
    <option value="alrajhi_est_5">مصرف الراجحي - بناء ذاتي جديد</option>
    <option value="arabi_ind"> البنك العربي </option>
   
    